name: watai
channels:
  - conda-forge
dependencies:
  - python=3.10.4
  - pip
  - xarray
  - cartopy
  - matplotlib
  - scikit-learn
  - zarr
  - dask
  - plotly
  - huggingface_hub
  - cupy
  - ipdb
  